apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LitvinchukRoman/FormaTest.git
    targetRevision: HEAD
    path: helm-charts/victoria-metrics-stack

    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "helm.dependency-update"
          value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

