apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/LitvinchukRoman/FormaTest.git
    targetRevision: HEAD
    path: bootstrap-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
